export const NEWS_SOURCES = [
  {
    name: "Premium Times",
    baseUrl: "https://www.premiumtimesng.com",
    feed: "https://www.premiumtimesng.com/feed",
    category: "news",
    region: "National",
  },
  {
    name: "The Punch",
    baseUrl: "https://punchng.com",
    feed: "https://rss.punchng.com/v1/category/latest_news",
    category: "news",
    region: "National",
  },
  {
    name: "Vanguard",
    baseUrl: "https://www.vanguardngr.com",
    feed: "https://www.vanguardngr.com/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Daily Trust",
    baseUrl: "https://dailytrust.com",
    feed: "https://dailytrust.com/feed/",
    category: "news",
    region: "Northern",
  },
  {
    name: "Leadership",
    baseUrl: "https://leadership.ng",
    feed: "https://leadership.ng/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Channels TV",
    baseUrl: "https://www.channelstv.com",
    feed: "https://www.channelstv.com/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Daily Post",
    baseUrl: "https://dailypost.ng",
    feed: "https://dailypost.ng/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Nigerian Tribune",
    baseUrl: "https://tribuneonlineng.com",
    feed: "https://tribuneonlineng.com/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "BusinessDay",
    baseUrl: "https://businessday.ng",
    feed: "https://businessday.ng/feed/",
    category: "news",
    region: "Business",
  },
  {
    name: "PM News",
    baseUrl: "https://pmnewsnigeria.com",
    feed: "https://pmnewsnigeria.com/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Ripples Nigeria",
    baseUrl: "https://www.ripplesnigeria.com",
    feed: "https://www.ripplesnigeria.com/feed/",
    category: "news",
    region: "National",
  },
  {
    name: "Information Nigeria",
    baseUrl: "https://www.informationng.com",
    feed: "https://www.informationng.com/feed",
    category: "news",
    region: "National",
  },
  {
    name: "TheCable",
    baseUrl: "https://www.thecable.ng",
    feed: "https://www.thecable.ng/feed",
    category: "news",
    region: "National",
    botBlocked: true,
  },
  {
    name: "The Guardian Nigeria",
    baseUrl: "https://guardian.ng",
    feed: "https://guardian.ng/feed/",
    category: "news",
    region: "National",
    botBlocked: true,
  },
  {
    name: "Dubawa",
    baseUrl: "https://dubawa.org",
    feed: "https://dubawa.org/feed/",
    category: "factcheck",
    region: "National",
    ifcn: true,
  },
  {
    name: "FactCheckHub",
    baseUrl: "https://factcheckhub.com",
    feed: "https://factcheckhub.com/feed/",
    category: "factcheck",
    region: "National",
    ifcn: true,
  },
  {
    name: "FactCheck Africa",
    baseUrl: "https://factcheckafrica.net",
    feed: "https://factcheckafrica.net/feed/",
    category: "factcheck",
    region: "National",
    ifcn: true,
  },
];

export function getSourcesByCategory(category) {
  return NEWS_SOURCES.filter((s) => !category || s.category === category);
}
